spring:
  application:
    name: user-server
  devtools:
    restart:
      enabled: true
  boot:
    admin:
      client:
        url: "http://localhost:8011"
        username: admin
        password: admin
        instance:
          prefer-ip: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    health-check-url-path: /actuator/health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS