schdule:
  persistence: true
  thread-pool:
    size: 5
  datasource:
    url: jdbc:mysql://localhost:3306/link_task?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql